### ISSUE TITLE
Error warning missing wallet_events

### ISSUE THREAD

**Issue by Hbitvof** [martomi/chiadog#117]
Hi,

Today I upgraded to version 0.5.0. When starting Chiadog now I see an error:

![image](https://user-images.githubusercontent.com/41229269/118236457-635c0080-b496-11eb-9847-50709228ee04.png)

I don't see an instruction in the upgrade notes what to add to the config.yaml.

**Comment by martomi** [comment]
Apologies for unclear instructions.

In this [diff view](https://github.com/martomi/chiadog/commit/4c63c9d07f0fc8e4150de2a655ef0b29d6f4470f#diff-0997963b54113de6bb19667e1ad7c561a2e6cbba874d4fe671c3e116252f3d25) you can see what lines were added to the config file.

You need to add `wallet_events: true` for each notifier that you are using.
