### ISSUE TITLE
Add hostname of system to alerts

### ISSUE THREAD

**Issue by Thr3d** [martomi/chiadog#139]
When running chiadog for multiple harvesters it would be helpful to have the hostname (or variable in config) added to the alerts to define which system an alert is for.

**Comment by pieterhelsen** [comment]
It is already possible to set a notification prefix in the config.yaml

```yaml
# This is useful to differentiate multiple chiadog
# instances monitoring multiple harvesters
notification_title_prefix: 'Chia'
```

You could pass in the hostname there.
