### ISSUE TITLE
Support for pinging a server by IP address?

### ISSUE THREAD

**Issue by Foxh0und** [martomi/chiadog#146]
Due to the use of Urllib, we can't open IP addresses for the keep alive. 

`Failed to ping keep-alive: unknown url type: '10.25.160.151' (keep_alive_monitor.py:116)`

**Environment:**
 - OS: Raspbian Buster
 - Python version: 3.7

**Comment by Foxh0und** [comment]
@martomi I have a branch ready to go for this, if I could have permission, that would be great.

**Comment by martomi** [comment]
@Foxh0und You can fork the repository, push your fixes on a branch there and open a PR to this repository directly from the fork. It doesn't require you to have any extra access.
