### ISSUE TITLE
Add a "plot count changed" threshold.

### ISSUE THREAD

**Issue by sebmarchand** [martomi/chiadog#147]
I'm using plotman on my plotters and I've enabled the option to sync my plots to a remote machine (my main storage server). Because of this the total plot count on the plotters sometime decrease by 1 (once a plot has been successfully synced). It'd be quite useful to add a config option to specify a threshold when reporting a "plot count changed" warning (e.g. don't emit it if the plot count dropped by only 1 or 2).

What do you think of this?

**Comment by martomi** [comment]
There was a similar request somewhere (can't find it now). Happy to add this if someone submits a PR with configurable threshold!

**Comment by sebmarchand** [comment]
Great, I'll take a look at this then. I wanted to make sure that you are fine with the idea before implementing it :)

**Comment by sebmarchand** [comment]
It looks like some refactoring is needed to make the config accessible from the log handlers, I'll see how to do this later today or this weekend.

**Comment by richardwhatever** [comment]
50% of all my alerts are of this nature - it basically swamps my phone notifications, so this feature would be very valuable. thanks!

**Comment by pieterhelsen** [comment]
Duplicate of #58
