### ISSUE TITLE
🚨 Chia HARVESTER Your harvester appears to be offline! No events for the past 2403 seconds.

### ISSUE THREAD

**Issue by VinsTitan** [martomi/chiadog#149]
I have this warning massage when chiadog is running. I set up only  file_log_consumer and telegram notifier that report the same warning. What is wrong?

Environment:
 - OS:  Win10
 - Python version: 3.9
 - Chia version: 1.1.5

**Comment by martomi** [comment]
This is a long-standing issue with Win10. See https://github.com/martomi/chiadog/issues/72
I'm using `chiadog` on Linux only and Windows is currently only under experimental support.
