### ISSUE TITLE
Discord notification - working but confusing

### ISSUE THREAD

**Issue by digitalkisan** [martomi/chiadog#161]
Is there a way to add an identifier to each notification. I have 2 machines running and the it would be really helpful to see which machine is generating a warning pushed to discord
for example

**Machine1** -Chia HARVESTER
Your harvester appears to be offline! No events for the past 900 seconds.
**Machine2**- Chia HARVESTER
Your harvester appears to be offline! No events for the past 900 seconds.

Thanks all

**Comment by pieterhelsen** [comment]
Hi, this is already present in the config file.

```yaml
# This is useful to differentiate multiple chiadog
# instances monitoring multiple harvesters
notification_title_prefix: 'Chia'
```

**Comment by digitalkisan** [comment]
Thanks , don't know how i didn't spot that!
