### ISSUE TITLE
1.1.6 : Experiencing networking issues? Skipped 2+ signage points in the last hour.

### ISSUE THREAD

**Issue by Yamanipanuchi** [martomi/chiadog#162]
Just upgraded my farm to 1.1.6, First time having the script in action. Love the idea.

I've been getting "Experiencing networking issues? Skipped 2+ signage points in the last hour." warnings. I dont know exactly what this means?

**Comment by Yamanipanuchi** [comment]
I just checked the logs.

2021-05-21T12:35:29.627 full_node chia.full_node.full_node: INFO     ⏲️  Finished signage point 36/64:

Its in there...

**Comment by Yamanipanuchi** [comment]
It looks like this message popped up when this came up in the logs....

2021-05-21T15:30:58.714 full_node chia.full_node.full_node: INFO     Don't have signage point {'challenge_hash':

**Comment by josinaldobarbosa** [comment]
in the previous version it already happened to me, does anyone know what that means?

**Comment by martomi** [comment]
This is duplicate with: https://github.com/martomi/chiadog/issues/145 Please refer to the discussion there
