### ISSUE TITLE
Hourly Update?

### ISSUE THREAD

**Issue by Yamanipanuchi** [martomi/chiadog#163]
Might be much, But I wouldn't mind having an hourly update option. Maybe being able to select where the hourly goes and where the daily goes.

Otherwise, Love the script! Adds peace of mind "Is it running?"

**Comment by VanQz** [comment]
Yes. Would be good if we can have a update option such that we can specify when we want to have the update. maybe 12 and 1800 hours. Would be good if we can have minutes instead of just hours too!

**Comment by martomi** [comment]
Duplicate with https://github.com/martomi/chiadog/issues/69 please move discussion there.
