### ISSUE TITLE
Harvester appears to be offline yet the logs says otherwise ???

### ISSUE THREAD

**Issue by runechronos** [martomi/chiadog#165]
**Describe the bug**

A clear and concise description of what the bug is and how it can be reproduced.

**Environment:**
 - OS: Win10 x64
 - Python version: 3.7
 - PIP version: 
 - Chia version: 1.1.6

Hy, I don't understand, I'm using now chia 1.1.6, and I get the 'your harvester appears to be offline all the time, yet in the logs it seems not to be offline look at the picture:

![PXL_20210522_060035584](https://user-images.githubusercontent.com/9034096/119216407-d509ff00-bad3-11eb-84bf-0b5125473c70.jpg)

Any clue ? Is it a bug or is the harvester really not working ? What I'm an i do to check it for sure (chia command ?)

Thx in advance

**Comment by martomi** [comment]
Known bug on Windows, see: https://github.com/martomi/chiadog/issues/72

We have a fix in the pipeline: https://github.com/martomi/chiadog/pull/164
If you know your way around with git, you can already test it, otherwise a new release should be coming this Sunday.
