### ISSUE TITLE
Support reward notifications for more scenarios 

### ISSUE THREAD

**Issue by dvic** [martomi/chiadog#167]
I believe that if you follow the best practice of using a separate (offline) wallet (describe here https://github.com/Chia-Network/chia-blockchain/wiki/Good-Security-Practices-on-Many-Machines#keep-your-wallet-separate) you won't get notified (because the wallet logs won't contain the lines for the correct wallet)? Maybe it's a good idea to have a separate notification for when you have won and another one that watches the wallet logs?

**Comment by martomi** [comment]
I'll hijack that issue and generalise it a little so that we have the full context in the same place.

The XCH notifications currently work only in the following scenario: 

> Running full node + harvester + wallet on the same machine and receiving rewards on that same wallet. 

These notifications are just a bonus on top of critical alerts in monitoring your harvesters, so resolving that won't be a priority from my side but contributions are welcome.

**Comment by martomi** [comment]
The low hanging fruit here is to bring back the "Found proof" notifications. I'll do that even though a found proof doesn't guarantee an actual reward. It's the best we can do that works for all possible setups.

**Comment by martomi** [comment]
Few notes for anyone possibly interested in tackling this:
- If harvester is running standalone, only "found proofs" events can be parsed out from the logs. However, finding a proof doesn't guarantee a reward.

**Comment by dvic** [comment]
Having the "found proof" notifications are enough for me for now. Thanks!

**Comment by Ganbin** [comment]
Hi,

Since we have the official pool protocol, finding proofs doesn't give much more info if we have found a block with a reward destination inna separated wallet.

The only usefull information in this case I have found in the debug log was this line : 

```
2021-07-24T16:01:42.245 full_node chia.full_node.full_node: INFO     Starting to make the unfinished block
2021-07-24T16:01:42.255 full_node chia.full_node.full_node: INFO     Made the unfinished block
2021-07-24T16:01:42.328 full_node chia.full_node.full_node: INFO     🍀 ️Farmed unfinished_block 409126291baa2debe79099cff716ac0aedc451354105ed2667dc1ddfed3d8be0, SP: 42, validation time: 0.04041004180908203, cost: 202394374
```

Could we consider to add such parser?

**Comment by Ganbin** [comment]
Actually the answer in https://github.com/martomi/chiadog/issues/252#issuecomment-878092188 would solve this issue.

Hope this will come soon :)
