### ISSUE TITLE
Skipped SPs unknown

### ISSUE THREAD

**Issue by tydeno** [martomi/chiadog#196]
**Skipped SPs shown as unknown**

I just received my second chiadog notification to discord. 

For the second time it shows the amount of skipped SPs as unknown. That actually is the metric i'm most interested in :P
![image](https://user-images.githubusercontent.com/83050419/119700495-94074700-be53-11eb-99ff-d2811e8f6f33.png)

May I be doing something wrong?

**Environment:**
 - OS: Windows 10 
 - Python version: 3.9.5
 - PIP version: 21.1.1
 - Chia version: 1.1.6

**Comment by pieterhelsen** [comment]
Are you running this on your full node or just a harvester? The harvester has no notion of signage points.

**Comment by tydeno** [comment]
@pieterhelsen Its a full node though.

**Comment by martomi** [comment]
Some people had chia configurations that splits the harvester and full node logs into separate files. I'd suggest that you double-check all your logs are going to `debug.log` as expected. If `chiadog` can find logs from the full node in `debug.log` it'll work. That functionality is covered by unit tests.

**Comment by tydeno** [comment]
I just double checked. My logs are  going `debug.log`. I also dont know a way how to separate those logs tbh.

**Comment by tydeno** [comment]
Hold on. Im running an older version. Darn. I'll close this for now.
