### ISSUE TITLE
[Feature] Add watcher for running plot processes

### ISSUE THREAD

**Issue by ems1985** [martomi/chiadog#202]
In the `config.yaml` it should be possible to define a certain number of chia plotting processes (e.g. `chia_plot_processes_warning_threshold`) and if the number of active processes falls below the threshold a warning notification should be sent out.

Similarly it should be possible to add a `plot_process_warning_time_m` and if a plot process ever goes over that time a warning notification should be sent out.

**Comment by martomi** [comment]
Thank you for the suggestion. There are many other tools specialising in plotting and monitoring these processes. Chiadog specializes in monitoring the harvesters (for now).
