### ISSUE TITLE
Startup fails after hard reboot of computer

### ISSUE THREAD

**Issue by Chardmw** [martomi/chiadog#205]
Startup fails after hard reboot of computer.  

When the computer does a hard reset the debug.log.offset file is not closed and removed. The startup of CHIADOG then hangs. See keybase://chat/chia_network.public#chiadog/2744 for example of the error received and the current fix action. 

Can there be a check during startup for this file and remove it if it exists before it hangs? 

**Environment:**
 - OS: Windows 10
 - Python version:
 - PIP version:
 - Chia version: 1.1.6

**Comment by martomi** [comment]
This is in 0.6.1 release now!
