### ISSUE TITLE
Once every day the chia-dog process seems to think my harvester is offline when it isnt

### ISSUE THREAD

**Issue by Mar-85** [martomi/chiadog#211]
Its happened almost every day where I havent manually restarted the chia-dog process in powershell but it seems to think my harvester is offline when it isnt. A restart fixes it until the next day.

https://i.imgur.com/cYcJWf8.png
![image](https://user-images.githubusercontent.com/25620696/120099040-34e65280-c131-11eb-80ba-fdf51790c6bd.png)

A clear and concise description of what the bug is and how it can be reproduced.

**Environment:**
 - OS: Win 10
 - Python version: 3.9.5
 - PIP version: 21.1.1
 - Chia version: [0.5.1] - 2021-05-17

**Comment by pieterhelsen** [comment]
Hi,

We recently released Chiadog 0.6.0, which specifically addresses this issue. Please try upgrading, following the instructions [here](https://github.com/martomi/chiadog#updating-to-the-latest-release) and let us know if that fixes the issue for you.

**Comment by Mar-85** [comment]
> Hi,
> 
> We recently released Chiadog 0.6.0, which specifically addresses this issue. Please try upgrading, following the instructions [here](https://github.com/martomi/chiadog#updating-to-the-latest-release) and let us know if that fixes the issue for you.

Hi, thanks for replying. I didnt realize it was a known issue. I will upgrade today and feedback tomorrow.

**Comment by Mar-85** [comment]
> Hi,
> 
> We recently released Chiadog 0.6.0, which specifically addresses this issue. Please try upgrading, following the instructions [here](https://github.com/martomi/chiadog#updating-to-the-latest-release) and let us know if that fixes the issue for you.

Sorry, i see those upgrade instructions are for linux. What is the upgrade instructions if using in windows?

**Comment by pieterhelsen** [comment]
There you go:
https://github.com/martomi/chiadog/blob/main/WINDOWS.md

**Comment by Mar-85** [comment]
> There you go:
> https://github.com/martomi/chiadog/blob/main/WINDOWS.md

About 24hrs later and no issues....also a lot of the error messages have stopped also. Thanks!

**Comment by pieterhelsen** [comment]
Happy to help! 💯
