### ISSUE TITLE
Skipped SPs are always reported as `Unknown`

### ISSUE THREAD

**Issue by roadhero** [martomi/chiadog#215]
**Skipped SPs in reports are always displayed as Unknown**

Running the latest versions of Chiadog, Chia and Python/pip/requirements on a farmer+harvester machine. No issues while running chiadog itself and parsers are indeed launched. Skipped SPs are always displayed as Unknown in reports, and even though there are no issues indeed, I guess the reports should display None? Reporting as a bug, as I'm pretty sure there are no issues with the setup itself:

**Environment:**
 - OS: Windows 10
 - Python version: 3.9.5
 - PIP version: 21.1.2
 - Chia version: 1.1.6

**Comment by martomi** [comment]
This is expected when running on farmer/harvester. The signage point information is only available on the full node.
