### ISSUE TITLE
help with this error please on Windows. 

### ISSUE THREAD

**Issue by luisfgbb** [martomi/chiadog#228]
Traceback (most recent call last):
  File "C:\Users\Z840\chiadog\main.py", line 12, in <module>
    from src.chia_log.handlers.daily_stats.stats_manager import StatsManager
  File "C:\Users\Z840\chiadog\src\chia_log\handlers\__init__.py", line 14, in <module>
    from .daily_stats.stats_manager import StatsManager
  File "C:\Users\Z840\chiadog\src\chia_log\handlers\daily_stats\__init__.py", line 5, in <module>
    from ...parsers.finished_signage_point_parser import FinishedSignagePointMessage
  File "C:\Users\Z840\chiadog\src\chia_log\parsers\finished_signage_point_parser.py", line 9, in <module>
    from dateutil import parser as dateutil_parser
ModuleNotFoundError: No module named 'dateutil'

image my code. https://ibb.co/C0qKJjg

**Environment:**
 - OS:  windows 10
 - Python version: 3.9
 - PIP version:
 - Chia version: 1.1.7

**Comment by aitorserra** [comment]
I have the same error. Did you find a solution? Thanks.

**Comment by martomi** [comment]
@aitorserra ython-dateutil is one of the requirements, see: https://github.com/martomi/chiadog/blob/429b90cf2d3f74a885d4ffcb748fb63b1521e48b/requirements.txt#L2

You either haven't installed the requirements (as part of the described setup process), or you have installed them inside virtual environment, but trying to run `chiadog` outside that environment.

**Comment by olnev** [comment]
Installed last chiadog, edited config. After running start.cmd got:
`ModuleNotFoundError: No module named 'dateutil'`
However:
`C:\chiadog>pip3 install python-dateutil
Requirement already satisfied: python-dateutil in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\me\appdata\local\programs\python\python39\lib\site-packages (from python-dateutil) (1.16.0)`
