### ISSUE TITLE
How to finfd those plots that took longer than 5 sec.?

### ISSUE THREAD

**Issue by jkoenig72** [martomi/chiadog#234]
Hi,

thansk for proviging this nice tool. Really like it.

Just need some hints how to improve my setup - 

- average: 1.12s over 2999 searches
- over 5s: 63 occasions (2.1%)
- over 15s: 43 occasions (1.4%)
Plots 🌱: 1781, new: 16
Eligible plots 🥇: 3.47 average
Skipped SPs ⚠️: 1 (0.03%)

I get lots of those alerts >5 sec, normally in the range of 20 - 30 sec., how can I see which plot is responsible for that?

Also - those numbers above, are they in general ok? Have not got any chia so far, just wondering if this is bad luck or the setup is weak.

Any feedback?

Regards
Joerg

**Comment by pieterhelsen** [comment]
This is usually not so much a problem with your plots (though you can run `chia plots check` just to be sure), but rather a problem with your hardware setup.

Are you plotting and farming at the same time? For a farm that size, it is recommended to split that up into two separate instances.

**Comment by jkoenig72** [comment]
Hi,

thanks for coming back to me...

I have that split up. Using a hp ProLiant dl580 for the farming, I switched
off the plotting on that machine. plots are on HDDs, mostly sata / usb3,
all directly connected to that machine and mounted each disk into an extra
folder. Two external shares I have mounted via nfs (synology and some other
hp proliant server), so wondering where I can see what plots causing those
warnings... can't be sata, can't be usb3 - its maybe the Synology....

Any idea how I can find out?

**Comment by jkoenig72** [comment]
I will remove those 2 nfs shares and see if those warnings will go away...

**Comment by pieterhelsen** [comment]
In the Chia log you'll find entries such as 

```
2021-06-10T10:05:13.146 harvester chia.harvester.harvester: INFO     0 plots were eligible for farming 8f9e872de0... Found 0 proofs. Time: 0.10962 s. Total 134 plots
```

So in the default 'INFO' log you won't be able to find which plots specifically have been searched. 
You can try setting the log level for Chia to DEBUG instead; this might output which plots are searched.
`chia configure -log_level DEBUG`

**Comment by jkoenig72** [comment]
Thanks!

**Comment by jkoenig72** [comment]
I removed the nfs shares - no warnings... I guess it's the synology. pretty
old...

**Comment by jkoenig72** [comment]
Seems also important to keep those machines (if they are a bit old) "clean"
of heavy work, like running docker or something. Just sharing the files.
