### ISSUE TITLE
Scripts disabled on this system

### ISSUE THREAD

**Issue by aitorserra** [martomi/chiadog#235]
I'm getting this error, any idea about what it's? Thanks.

C:\Users\aitor\chiadog> . .\venv\Scripts\activate
. : No se puede cargar el archivo C:\Users\aitor\chiadog\venv\Scripts\Activate.ps1 porque la ejecución de scripts está
deshabilitada en este sistema. Para obtener más información, consulta el tema about_Execution_Policies en
https:/go.microsoft.com/fwlink/?LinkID=135170.
En línea: 1 Carácter: 3
+ . .\venv\Scripts\activate
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by F1DNA** [comment]
Probably this:

PS C:\Windows\system32> Get-ExecutionPolicy
Restricted
PS C:\Windows\system32> Set-ExecutionPolicy RemoteSigned

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
PS C:\Windows\system32> Get-ExecutionPolicy
RemoteSigned
PS C:\Windows\system32>

**Comment by F1DNA** [comment]
If that doesn't work and you want to live dangerously, you can:

Set-ExecutionPolicy Bypass

I don't chia on windows so not sure what policy you actually need here.  remotesigned hopefully is what you need

**Comment by martomi** [comment]
Have you tried the [start.cmd](https://github.com/telegram-rs/telegram-bot/issues/236#issuecomment-822483434) script? It should set the correct execution policy automatically.
