### ISSUE TITLE
Request:  Compatibility with Chia Forks and Additional Configuration Option

### ISSUE THREAD

**Issue by djjaeger82** [martomi/chiadog#242]
Could you add compatibility with some of the 3rd party chia-forks?  (spare, flax, chaingreen)  Just updating the logs directory in the config doesn't seem to work

Also, on config, could you give us more options for some of the warnings?  For example, I often get a "plots decreased by 2" error when I'm transferring plots from my plotter to external HDDs in pairs.  It would be nice if we could set that threshold.

Configuring warning for response times being too slow would be nice as well for the users.

**Comment by djjaeger82** [comment]
Could you also please give the plot location when a plot fails for seeking too long?  That extra info in the alert would make it easier to troubleshoot which drives are acting up...

**Comment by digitalspaceport** [comment]
Any update on status?

**Comment by guydavis** [comment]
Hi all, I just added a [pull request](https://github.com/martomi/chiadog/pull/302) to support blockchain forks such as Flax, HDDCoin, Chives, and NChain among others in the future.

**Comment by martomi** [comment]
Decided this won't be supported in the main repo for reasons explained [here](https://github.com/martomi/chiadog/discussions/344#discussioncomment-3109917)
