### ISSUE TITLE
No notifications coming

### ISSUE THREAD

**Issue by cyperbg** [martomi/chiadog#249]
Just installed ChiaDog on my Ubuntu farmer machine and it doesn't seem to send any notifications.

I setup email notification like this:

> smtp:
>     enable: true
>     daily_stats: true
>     wallet_events: true
>     credentials:
>       sender: 'email@myowndomain.org'
>       sender_name: 'ChiaDog'
>       recipient: 'contact@myowndomain.org'
>       username_smtp: 'email@myowndomain.org'
>       password_smtp: 'password'
>       host: 'mail.supremecluster.com'
>       port: 25

Also setup Pushover:

>   pushover:
>     enable: true
>     daily_stats: true
>     wallet_events: true
>     credentials:
>       api_token: 'a1umy3vy734efadefue79b52xo2di'
>       user_key: 'ugnseb1cp345effdz9ioxvuucbjfebe'

It is supposed to send notifications at midnight, but nothing happened:

> daily_stats:
>   enable: true
>   time_of_day: 0
>   frequency_hours: 24

Terminal just stays at:

> [2021-06-30 01:50:49] [    INFO] --- Starting Chiadog (v0.6.0) (main.py:54)
> [2021-06-30 01:50:49] [    INFO] --- Enabled local file log consumer. (log_consumer.py:59)
> [2021-06-30 01:50:49] [    INFO] --- Keep-alive check period: 300 seconds (keep_alive_monitor.py:45)
> [2021-06-30 01:50:49] [    INFO] --- Initializing Pushover notifier. (pushover_notifier.py:13)
> [2021-06-30 01:50:49] [    INFO] --- Initializing Email notifier. (smtp_notifier.py:16)
> [2021-06-30 01:50:49] [    INFO] --- Enabled stats for daily notifications (stats_manager.py:37)
> [2021-06-30 01:50:49] [    INFO] --- Summary notifications will be sent out every 24 hours starting from 0 o'clock (stats_manager.py:48)
> [2021-06-30 01:50:49] [    INFO] --- Enabled parser for harvester activity - eligible plot events. (harvester_activity_parser.py:32)
> [2021-06-30 01:50:49] [    INFO] --- Enabled check for farming events. (time_since_last_farm_event.py:22)
> [2021-06-30 01:50:49] [    INFO] --- Enabled check for non-decreasing total plot count. (non_decreasing_plots.py:18)
> [2021-06-30 01:50:49] [    INFO] --- Enabled check for time taken to respond to challenges. (quick_plot_search_time.py:18)
> [2021-06-30 01:50:49] [    INFO] --- Enabled check for found proofs. (found_proofs.py:15)
> [2021-06-30 01:50:49] [    INFO] --- Enabled parser for finished signage points. (finished_signage_point_parser.py:28)
> [2021-06-30 01:50:49] [    INFO] --- Enabled check for finished signage points. (non_skipped_signage_points.py:19)
> [2021-06-30 01:50:49] [    INFO] --- Enabled parser for wallet activity - added coins. (wallet_added_coin_parser.py:26)
> [2021-06-30 01:50:50] [    INFO] --- Detected new plots. Farming with 3961 plots. (non_decreasing_plots.py:26)

**Comment by kanasite** [comment]
[2021-06-30 01:50:49] [ INFO] --- Summary notifications will be sent out every 24 hours starting from 0 o'clock (stats_manager.py:48)

u will have to wait until the following day 00:00

**Comment by kanasite** [comment]
Otherwise u can checkout the dev branch and set the time_of_day under config

https://github.com/martomi/chiadog/pull/237

**Comment by martomi** [comment]
Logs look good. There's not enough information to reproduce the issue. Please re-open if you have more insights.
