### ISSUE TITLE
[BUG] Signage Points are not parsed on Windows 

### ISSUE THREAD

**Issue by pwf1986** [martomi/chiadog#253]
While running CHIA in windows, chiadog seems to miss INFO about signage points. I think the issue might be related to a missing symbol in windows chia debug log file related to signage points vs. in linux. 

![Chiadog SPs](https://user-images.githubusercontent.com/87129699/124918633-8cf85a80-dff5-11eb-9a4a-30ea2acddb33.png)

**Comment by pieterhelsen** [comment]
Additional info in case someone other than me picks up this issue. It seems to be related to the emoji that's used in the Posix logfile:

**Posix**
`2021-07-08T13:56:28.731 full_node chia.full_node.full_node: INFO     ⏲️  Finished signage point 16/64: CC: ... RC: ...`

**Windows**
`2021-07-08T06:31:14.339 full_node chia.full_node.full_node: INFO       Finished signage point 11/64: CC: ... RC: ...`

This line should be changed to be multi-platform compliant or a switch should be included to use a different regex for Windows.
https://github.com/martomi/chiadog/blob/429b90cf2d3f74a885d4ffcb748fb63b1521e48b/src/chia_log/parsers/finished_signage_point_parser.py#L32

**Comment by martomi** [comment]
Now released in 0.6.1.
