### ISSUE TITLE
TypeError: unlink() got an unexpected keyword argument 'missing_ok'

### ISSUE THREAD

**Issue by springjools** [martomi/chiadog#264]
**Describe the bug**
In main.py, line 58:
 Config.get_log_offset_path().unlink(missing_ok=True)

Python 3.7.3 hasn't implemented this parameter, cf: https://stackoverflow.com/questions/42636018/python-difference-between-os-remove-and-os-unlink-and-which-one-to-use

"In Python v3.8, a missing_ok argument was added to the Path.unlink() function. When *missing_ok* == True, an exception will not be raised if the file doesn't exist before trying to remove it."

Debian still uses python 3.7.3, I hope they would upgrade soon :)

A clear and concise description of what the bug is and how it can be reproduced.

**Environment:**
 - OS: Linux Debian 10 (Raspbian)
 - Python version: 3.7.3
 - PIP version:
 - Chia version: 1.2.2
 - Chiadog version:  0.6.1
 - Harvester: remote OR local

**Comment by springjools** [comment]
If you want you can disregard from this issue: I'm building python 3.9 from source for debian

**Comment by pieterhelsen** [comment]
Hi, thanks for the heads-up! 
Considering we currently still support Python 3.7, I would like to keep it open for now and release a bugfix soon.

**Comment by martomi** [comment]
Released with 0.7.0
