### ISSUE TITLE
Disable the "found x proofs" spam?

### ISSUE THREAD

**Issue by chadmccune** [martomi/chiadog#270]
Is there a way to disable only the "found x proofs on <node>" spam?  I have 4 harvesters in addition to my full node and I find proofs on all of them almost every 10 seconds...

Any real notifications get lost in the constant spam of "found proofs"

**Comment by lorado** [comment]
Please read other issues, before opening a new one. You will save others people time...

There is already an issue to update log parsing algorithm: #252, and also a temporarily workaround to stop spamming proofs found: https://github.com/martomi/chiadog/issues/252#issuecomment-877416135

**Comment by chadmccune** [comment]
While I appreciate the project, I don't appreciate the arrogance and
condescension.... I did search, I just did not find this specific item.

Thank you.

**Comment by lorado** [comment]
I didn’t want to be rude or unpolite and certainly not „arrogant“, sorry for that!

**Comment by chadmccune** [comment]
Apology accepted =)  Thanks for the project.
