### ISSUE TITLE
Rust is a required dependency, and without it, install fails without obvious reason

### ISSUE THREAD

**Issue by BasilHorowt** [martomi/chiadog#29]
Seems that `paramiko` requires rust to be present to install.  A few thoughts:

1) When not dealing with remote harvesters, is `paramiko` even required? Any ways to lighten the deps by optionally requiring that?
2) Can the install process fail nicely if rust is not present?
3) Can the docs mention that rest is a prereq?

**Comment by BasilHorowt** [comment]
I don't have the error in front of me but it was essentially this https://cryptography.io/en/latest/faq/#installing-cryptography-fails-with-error-can-not-find-rust-compiler

**Comment by martomi** [comment]
I have no Rust installed on my machine. Seems it's only required when compiling `cryptography` package from source.

Did you try this suggestion from the link you posted?
```
You may be able to fix this by upgrading to a newer version of pip which will install a pre-compiled cryptography wheel
```

My `pip3` version is:

```
pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```

I might look into optional imports in the future, but for now that should be a much faster fix.

**Comment by alibosworth** [comment]
OK cool! my pi running 64 bit debian has `pip 18.1` installed apparently, which is years old at this point... interesting.  Feel free to close this out!

**Comment by martomi** [comment]
👍  I'll add it as a step in the README

```
python3 -m pip install --upgrade pip
```
