### ISSUE TITLE
Allow Multiple Pushover users/devices

### ISSUE THREAD

**Issue by Gunrunner101** [martomi/chiadog#290]
I tried to add another pushover section just under the orginal pushover section in the config.yaml.
  pushover:
    enable: ture
    daily_stats: true
    wallet_events: true
    credentials:
      api_token: 'tookoutforpost'
      user_key: 'tookoutforpost'

Chia dog would not load as a result.

Thank you
Andrew

**Comment by martomi** [comment]
Only a single pushover section is supported. If you need two, you could probably run two instances of chiadog with different configs.
