### ISSUE TITLE
No notification for "farmed unfinished_block"

### ISSUE THREAD

**Issue by fisch88** [martomi/chiadog#294]
OS: Ubuntu
Python version: 3.8
PIP version: 21.2.4
Chiadog 0.7
Harvester Local
Chia version: 1.2.6

Since yesterday I have added NFT plots and therefore I participate with a minimum part of my plots in a pool.
I received a win today and it was not reported by ChiaDog, I don't understand why.
In the log I find "farmed unfinished_block".
Finally, the daily report is this (I don't understand that I won with my solo farm:

ℹ️ ChiaNas1 DAILY
Hello farmer! 👋 Here's what happened in the last 24 hours:

Received ☘️: 0.000009908005 XCH
Proofs 🧾: 31 found!
  - 30 partials submitted 📑
  - 0 blocks found 📦
Search 🔍: 
  - average: 2.77s over 9285 searches
  - over 5s: 38 occasions (0.4%)
  - over 15s: 0 occasions (0.0%)
Plots 🌱: 14081
Eligible plots 🥇: 27.53 average
Skipped SPs ⚠️: 5 (0.05%)

**Comment by martomi** [comment]
Good catch, I believe this should be resolved by https://github.com/martomi/chiadog/pull/293 
Will be included in next release most likely.
