### ISSUE TITLE
Add notifiction when users farm a block

### ISSUE THREAD

**Issue by springjools** [martomi/chiadog#298]
Currently chiadog only notifies you of incoming cash and found proofs in the daily roundup, but there is not actually a notification when you farm an unfinished block.

See here:

![image](https://user-images.githubusercontent.com/5911982/135732220-23e7a5dd-d370-4386-acf3-028b8f46cb1e.png)

**Comment by springjools** [comment]
If you need text with how a farmed block text looks like in the logs, I can provide that.

**Comment by martomi** [comment]
Yes, please post the way the logs look like on your side to confirm the format.
@kanasite actually has submitted a fix for that a while ago, I was waiting for someone to confirm the format https://github.com/martomi/chiadog/pull/293 If you can confirm that, we can proceed to merge and release the bug fix.

**Comment by springjools** [comment]
Here: https://pastebin.com/PRR8w2E3

**Comment by springjools** [comment]
There are also these notifications:

![image](https://user-images.githubusercontent.com/5911982/135835291-a293f6e0-0907-4f5d-960e-916a7b9e7691.png)

0.25 xch to wallet
1.75 xch goes to pool wallet, wallet #2 I think
then the pool payout of course

I wonder if it would be somehow possible to detect that the 1.75 xch isn't actuallky claimable by the user, if you are in a pool.

**Comment by martomi** [comment]
Thanks, I confirmed the message format and merged the linked PR, it'll be available in the next release (within 1-2 weeks).
Re: wallet notifications, it's not planned to do any extra detection there. Note that there's a config option to disable wallet events which is useful for pool users as these wallet events are very frequent.
