### ISSUE TITLE
Extra configuration

### ISSUE THREAD

**Issue by coderasm** [martomi/chiadog#38]
I had to do two extra bits of configuration before I could get chiadog to work with a remote harvester.
First I had to add the remotes harvester's ssh fingerprints to my known hosts file using:
`ssh-keyscan -H harvester_IP >> ~/.ssh/known_hosts`
Then I had to add a banner to my harvester's ssh server by adding this line to /etc/ssh/sshd_config:
`Banner /etc/ssh/my_banner`
Then I had to create that banner file with any text inside it using:
`echo "My banner" >> /etc/ssh/my_banner`
Then restart sshd using:
`systemctl restart sshd`

**Comment by martomi** [comment]
I don't see how the banner is necessary for that setup, can you elaborate why you had to do that?

Adding the fingerprints is probably easier / can be combined with testing the SSH into the machine with the keys, it'll ask you to add the machine to the known hosts file automatically on the first try.

**Comment by coderasm** [comment]
I did not have the harvester host fingerprints on my farmer because my farmer had never connected to my harvester using ssh.
I had received this banner protocol error. I was able to solve it by adding a banner.
https://github.com/paramiko/paramiko/issues/965

**Comment by martomi** [comment]
Interesting, what OS do you run on the remote harvesters?

**Comment by coderasm** [comment]
My harvester machine is manjaro/arch. Monitoring is done on my farmer/node which is ubuntu server on a pi 4.

**Comment by coderasm** [comment]
A large part of my host fingerprint problem came from the fact I use putty on windows to connect to all my machines. I had to copy the linux version of my putty private key to the farmer. I only ended up doing that after already adding host fingerprints using `ssh-keyscan -H harvester_IP >> ~/.ssh/known_hosts`. You are right, I probably could have just tried connecting after adding my private key to the farmer to get the host fingerprint instead of running ssh-keyscan. I ran the keysan command first because I encountered this error before adding my private key and attempting to connect from the farmer, `paramiko.ssh_exception.SSHException: Server '10.0.0.14' not found in known_hosts`.

**Comment by martomi** [comment]
Gotcha! Thanks for sharing your experiences, as you can see further up, I've added a point in the README now that hints towards logging in over SSH once to add fingerprints. Will keep in mind the other things if someone encounters similar issues 👍
