### ISSUE TITLE
failed building wheel for pynacl

### ISSUE THREAD

**Issue by charbob** [martomi/chiadog#44]
Apologies if this is an issue with my machine and not with Chiadog. I'm running Ubuntu 20.04.2 LTS on a Raspberry Pi 4B. When I run the `pip3 install wheel && pip3 install -r requirements.txt` command, I get an error: `ERROR: Could not build wheels for pynacl which use PEP 517 and cannot be installed directly`. Are there any suggestions on how to fix this?

Again, sorry if this isn't the right place to post this, I'm both new to Linux and Github. Cheers!

**Comment by martomi** [comment]
In general, this is the correct place. Though, the issue you're experiencing seems to be specific to your setup and not directly related to `chiadog`. I'd suggest to first try googling the error to see how others have resolved it.

Every setup is slightly different so you'll need to tinker a bit to figure out what's wrong. If the issue still persists after that, please summarise your findings, what version of python and pip you're running and it might be easier for someone to provide you with additional ideas for debugging.

**Comment by greimela** [comment]
@charbob I ran into the same issue, it occurs when you are missing the development dependencies for python.

Try to install them with
```
sudo apt install libpython3-dev build-essential
```

**Comment by charbob** [comment]
@greimela Thanks for the response, I tried to run it, but got an error:
```
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 build-essential : Depends: libc6-dev but it is not going to be installed or
                            libc-dev
                   Depends: g++ (>= 4:9.2) but it is not going to be installed
 libpython3-dev : Depends: libpython3.8-dev (>= 3.8.2-1~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by greimela** [comment]
@charbob Looks like some of your packages are broken, which is definitely out of scope of this project.
You could try to reinstall Ubuntu, or search the internet for a solution, for example [here](https://askubuntu.com/questions/963527/error-build-essential-depends-g-44-4-3-but-it-is-not-going-to-be-ins).

**Comment by charbob** [comment]
@greimela Reinstalling Ubuntu worked! Thanks so much for your help.
