### ISSUE TITLE
Number of plots chaning (non_decreasing_plots) to a variable

### ISSUE THREAD

**Issue by chia-dev** [martomi/chiadog#58]
Hi,

If you are plotting and farming on the same machine the number of plots will go up and down causing an alert.

I have changed my code in non_decreasing_plots.py from:
        if obj.total_plots_count < self._max_farmed_plots:
to
        if abs(obj.total_plots_count - self._max_farmed_plots) >= 5:    

That way if I loose a full drive, or many plots I will get alerted but not be bothered when plot jobs finis.

Reading the value from the config file seems like a better longer term option

Thanks

**Comment by martomi** [comment]
Are you moving plots to other machines? Usually notifications are only send for decreasing plot numbers. Increasing number of plots from plotting don't cause notifications.

**Comment by richardwhatever** [comment]
I'm running chiadog on my plotting machines (that run plotman) and they also act as harvesters, and this alert is constant (and frustrating). @chia-dev's suggestions would avoid this.

**Comment by richardwhatever** [comment]
any sense of if/when this might be resolved. This alerts just drowns out all my other notifications in a deluge.

**Comment by martomi** [comment]
Increasing threshold from 1 to 2 should resolve 99% the issues
