### ISSUE TITLE
Script Notifier

### ISSUE THREAD

**Issue by akeslo** [martomi/chiadog#66]
**Describe the bug**

I cannot get the script notifier to work properly, receiving the below error, can you please share a sample script?

`[   ERROR] --- Failed to send events over script: [Errno 8] Exec format error: '/Users/user1/Desktop/chiadog/restart_farm.sh' (notify_manager.py:64)`

**Environment:**
 - OS: Mac
 - Python version: 3.9.4
 - PIP version: 21.0.1
 - Chia version: 1.1.2

**Comment by martomi** [comment]
There's a sample script here: https://github.com/martomi/chiadog/blob/main/tests/test_script.sh Does that work for you?

**Comment by akeslo** [comment]
Yes, I was missing `#!/bin/bash`

Thank you!!
