### ISSUE TITLE
Feature reuqest: notify when the chiadog start to run

### ISSUE THREAD

**Issue by Umiiii** [martomi/chiadog#75]
Hi, I would like to request a feature, which allows chiadog to send a notification to any existed notifiy config. That would help people to check if they configure their notify channel correctly.

**Comment by tommoor** [comment]
This would be great – additionally it could be a flag `--notify` or similar on ./start as after the initial setup is done you might not need this going forward.

**Comment by VanQz** [comment]
This would be good to have! so we would know the program is running. and maybe a notification if possible for if the application is being terminated

**Comment by martomi** [comment]
This will be addressed as part of this issue https://github.com/martomi/chiadog/issues/69
Plan is to have daily summary option to immediately send one summary. Please continue discussion there.
