### ISSUE TITLE
Windows - Dev branch - WindowsPath not iterable

### ISSUE THREAD

**Issue by pdoteter** [martomi/chiadog#80]
**
I got this in the dev branch on line 76 of log_consumer.py

python popen argument of type 'WindowsPath' is not iterable

**Environment:**
 - OS: Windows 10
 - Python version: 3.9.5

** 
I changed the code on line 68 to:
        expanded_user_log_path = str(self._log_path.expanduser())

which fixes it.  I tried to push a branch with that small change for you guys to review, but I have no permission to push

**Comment by martomi** [comment]
Surprised this is an issue for Python 3.9.5 because according to the official docs, ]path-like objects are supported arguments by Popen](https://docs.python.org/3.8/library/subprocess.html#subprocess.Popen) since at least Python 3.8.0 🤔
